"""Detects the C++ compiler Bazel's auto-configured toolchain runs.

The toolchain is chosen by CC/CXX alone. Everything that follows from which
compiler that turns out to be -- its language level, whether it has static
reflection, and where its std module source lives -- is measured here and written
to @arc_cc_info//:cc_info.bzl for ARC's rules, rather than spelled out per
compiler in .bazelrc. Pointing CC/CXX at another compiler is the whole switch.
"""

_CC_INFO = """
# Generated by @arc//bazel:cc_detect.bzl from {cxx}. Do not edit.

COMPILER = {compiler}
VERSION = {version}
REFLECTION = {reflection}

# Put ahead of --cxxopt on every module compile, so a --cxxopt still wins.
CXXOPTS = {cxxopts}

# Linked into every binary through @arc//bazel:cc_link_flags, which every
# cpp_module depends on.
LINKOPTS = {linkopts}

GCC_STD_CPPM = {gcc_std}
CLANG_STD_CPPM = {clang_std}
"""

def _cxx_for(rctx):
    """The C++ driver to probe: CXX, else the one CC names, else g++."""
    cxx = rctx.getenv("CXX")
    if cxx:
        return cxx
    cc = rctx.getenv("CC") or "gcc"
    base = cc.split("/")[-1]
    head = cc[:len(cc) - len(base)]
    if base.startswith("clang") and not base.startswith("clang++"):
        return head + "clang++" + base[len("clang"):]
    if base.startswith("gcc"):
        return head + "g++" + base[len("gcc"):]
    return cc

def _predefined(rctx, cxx, flags):
    """The compiler's predefined macros under `flags`, or None if it rejects them."""
    res = rctx.execute([cxx] + flags + ["-dM", "-E", "-x", "c++", "/dev/null"])
    if res.return_code != 0:
        return None
    macros = {}
    for line in res.stdout.splitlines():
        parts = line.split(" ", 2)
        if len(parts) == 3 and parts[0] == "#define":
            macros[parts[1]] = parts[2]
    return macros

def _identify(macros):
    if "__clang__" in macros:
        return "clang", ".".join([macros["__clang_major__"], macros["__clang_minor__"],
                                  macros["__clang_patchlevel__"]])
    if "__GNUC__" in macros:
        return "gcc", ".".join([macros["__GNUC__"], macros["__GNUC_MINOR__"],
                                macros["__GNUC_PATCHLEVEL__"]])
    return "unknown", ""

def _gcc_std_cppm(rctx, cxx):
    """libstdc++'s bits/std.cc, found on the compiler's own include path: each
    libstdc++ ships its own, and one from another version will not import."""
    res = rctx.execute([cxx, "-v", "-E", "-x", "c++", "/dev/null"])
    in_search = False
    for line in (res.stderr or "").split("\n"):
        if "#include" in line and "search starts here" in line:
            in_search = True
            continue
        if "End of search list" in line:
            break
        if in_search and line.strip():
            candidate = line.strip() + "/bits/std.cc"
            if rctx.path(candidate).exists:
                return candidate

    # Fallback: broad filesystem search
    res = rctx.execute(["sh", "-c",
        "find /usr/include /usr/local/include /opt -name std.cc -path '*/bits/*' 2>/dev/null | sort -rV | head -1"])
    return res.stdout.strip() if res.return_code == 0 else ""

def _clang_std_cppm(rctx, clangxx):
    """libc++'s std.cppm, next to the resource directory of the clang in use."""
    res = rctx.execute([clangxx, "--print-resource-dir"])
    if res.return_code == 0:
        # resource_dir is like /usr/lib/llvm-21/lib/clang/21 -- go up 3 levels
        parts = [p for p in res.stdout.strip().split("/") if p]
        if len(parts) >= 3:
            candidate = "/" + "/".join(parts[:-3]) + "/share/libc++/v1/std.cppm"
            if rctx.path(candidate).exists:
                return candidate
    res = rctx.execute(["sh", "-c",
        "find /usr/lib/llvm-* -name std.cppm -path '*/libc++/v1/*' 2>/dev/null | sort -rV | head -1"])
    return res.stdout.strip() if res.return_code == 0 else ""

def _arc_cc_info_impl(rctx):
    rctx.getenv("PATH")  # which() below resolves through it
    cxx = _cxx_for(rctx)
    driver = rctx.path(cxx) if "/" in cxx else rctx.which(cxx)
    if not driver or not driver.exists:
        fail("arc_cc_info: C++ compiler '{}' not found; set CC/CXX".format(cxx))

    # Re-detect when the compiler behind the name changes, as an
    # update-alternatives switch does without touching CC/CXX.
    rctx.watch(driver)

    macros = _predefined(rctx, cxx, [])
    if macros == None:
        fail("arc_cc_info: '{}' failed to preprocess an empty file".format(cxx))
    compiler, version = _identify(macros)

    reflection = "__cpp_impl_reflection" in (
        _predefined(rctx, cxx, ["-std=c++26", "-freflection"]) or {})
    cxxopts = ["-std=c++26", "-freflection"] if reflection else ["-std=c++23"]
    linkopts = []
    if compiler == "gcc":
        cxxopts += ["-fdiagnostics-all-candidates", "-fconcepts-diagnostics-depth=6"]
        # A node may reach its host from its own constructor through MemberPtr,
        # backwards from `this`. At -flifetime-dse=2 GCC counts that read as one
        # of the node's still-dead *this and warns -Wuninitialized wherever the
        # read is inlined; level 1 drops only that constructor-entry assumption.
        cxxopts.append("-flifetime-dse=1")
        # GCC emits the static data members `import std` exports (std::string::npos
        # and the like) as strong symbols in every TU that imports it.
        linkopts.append("-Wl,--allow-multiple-definition")
        # std::stacktrace is defined in libstdc++exp, not libstdc++.
        if rctx.execute([cxx, "-print-file-name=libstdc++exp.a"]).stdout.strip().startswith("/"):
            linkopts.append("-lstdc++exp")
    elif compiler == "clang":
        cxxopts.append("-Wno-unused-command-line-argument")

    rctx.file("cc_info.bzl", _CC_INFO.format(
        cxx = str(driver),
        compiler = repr(compiler),
        version = repr(version),
        reflection = repr(reflection),
        cxxopts = repr(cxxopts),
        linkopts = repr(linkopts),
        gcc_std = repr(_gcc_std_cppm(rctx, cxx)),
        clang_std = repr(_clang_std_cppm(rctx, cxx if compiler == "clang" else "clang++")),
    ))
    rctx.file("BUILD", "exports_files([\"cc_info.bzl\"])\n")

arc_cc_info = repository_rule(
    implementation = _arc_cc_info_impl,
    local = True,
    configure = True,
    doc = "Detects the compiler CC/CXX name and the flags ARC's rules need for it.",
)
