"""Repository rule that scans C++20 module sources to build a precise dep map.

Runs bazel/scan_module_deps.py over the workspace source tree(s) and writes
a generated repository containing module_deps.bzl with:

  MODULE_DIRECT_DEPS      {module_name: [directly-imported module names]}
  FILE_DIRECT_DEPS        {workspace-rel-path: [directly-imported module names]}
  MODULE_SOURCES          {workspace-rel-path: module_name}
  MODULE_PROVIDER_TARGETS {module_name: bazel_target_label}

cpp_module.bzl loads these to compute the minimal PCM set needed by each
compilation action, so that modifying one module only recompiles actions
that genuinely depend on it.

When ARC is consumed as a bazel_dep, the scan walks BOTH the main workspace
(consumer) and ARC's own external workspace, so that ARC's modules
(e.g. arc.ixx) appear in the scan output with their canonical Bazel
short_path (../arc+/lib/modules/arc.ixx).
"""

def _arc_module_scan_impl(rctx):
    main_workspace = rctx.workspace_root

    # Scripts live in ARC's repo; resolve via label so consumers don't need to
    # copy them into their own bazel/ directory.
    script_path      = rctx.path(Label("@arc//bazel:scan_module_deps.py"))
    list_script_path = rctx.path(Label("@arc//bazel:list_module_files.py"))

    rctx.watch(script_path)
    rctx.watch(list_script_path)

    # Root descriptors: (absolute_path, short_path_prefix, repo_label_prefix)
    #   short_path_prefix: prefix prepended to MODULE_SOURCES / FILE_DIRECT_DEPS keys
    #   repo_label_prefix: prefix prepended to generated MODULE_PROVIDER_TARGETS labels
    roots = [(str(main_workspace), "", "")]

    # ARC's own workspace. When ARC is the main module this resolves to the
    # same path as main_workspace and is dropped to avoid double-walking.
    arc_module_path = rctx.path(Label("@arc//:MODULE.bazel"))
    arc_workspace = arc_module_path.dirname
    if str(arc_workspace) != str(main_workspace):
        canonical_name = arc_workspace.basename  # e.g. "arc+"
        roots.append((
            str(arc_workspace),
            "../" + canonical_name + "/",
            "@arc",
        ))

    # Watch only files that actually affect module deps:
    #   .ixx / .ixx.arc — module interface units and ARC DSL sources
    #   arc-embed .cpp  — .cpp files containing arc-begin/arc-end blocks
    #
    # CAVEAT: adding a brand-new .ixx/.ixx.arc file requires
    #   bazel clean --expunge
    # to force rediscovery (since we are not watching directory structure).
    list_args = ["python3", str(list_script_path)]
    for path, _, _ in roots:
        list_args.append("--root=" + path)
    list_result = rctx.execute(list_args, quiet = True)
    if list_result.return_code != 0:
        fail("arc_module_scan: file listing failed:\n" + list_result.stderr)

    for line in list_result.stdout.splitlines():
        f = line.strip()
        if f:
            rctx.watch(rctx.path(f))

    scan_args = ["python3", str(script_path)]
    for path, short_prefix, label_prefix in roots:
        scan_args.append("--root={}|{}|{}".format(path, short_prefix, label_prefix))
    result = rctx.execute(scan_args, quiet = True)

    if result.return_code != 0:
        fail("arc_module_scan: dep scan failed:\n" + result.stderr)

    rctx.file("module_deps.bzl", result.stdout)
    rctx.file("BUILD", "# Generated by arc_module_scan repository rule.\n")

arc_module_scan = repository_rule(
    implementation = _arc_module_scan_impl,
    local = True,
    doc = "Scans C++20 module source files and produces a module dependency map.",
)
