"""Repository rule that scans C++20 module sources to build a precise dep map.

Runs bazel/scan_module_deps.py over the workspace source tree and writes
a generated repository containing module_deps.bzl with:

  MODULE_DIRECT_DEPS      {module_name: [directly-imported module names]}
  FILE_DIRECT_DEPS        {workspace-rel-path: [directly-imported module names]}
  MODULE_SOURCES          {workspace-rel-path: module_name}
  MODULE_PROVIDER_TARGETS {module_name: bazel_target_label}

cpp_module.bzl loads these to compute the minimal PCM set needed by each
compilation action, so that modifying one module only recompiles actions
that genuinely depend on it.

arc_gen.bzl and cpp_module.bzl load MODULE_SOURCES and MODULE_PROVIDER_TARGETS
to automatically infer module names and dependency labels from source content,
eliminating the need for module_prefix / module_name / module_deps parameters.

Usage in MODULE.bazel:
  arc_module_scan = use_repo_rule("//bazel:module_scan.bzl", "arc_module_scan")
  arc_module_scan(name = "arc_module_deps")

Then in cpp_module.bzl:
  load("@arc_module_deps//:module_deps.bzl", "MODULE_DIRECT_DEPS", "FILE_DIRECT_DEPS")
"""

def _arc_module_scan_impl(rctx):
    workspace   = rctx.workspace_root
    script      = workspace.get_child("bazel").get_child("scan_module_deps.py")
    list_script = workspace.get_child("bazel").get_child("list_module_files.py")

    # Watch the scanner and file-lister scripts so changes to them re-trigger.
    rctx.watch(script)
    rctx.watch(list_script)

    # Watch only the files that actually affect module deps:
    #   .ixx / .ixx.arc — module interface units and ARC DSL sources
    #   arc-embed .cpp  — .cpp files containing arc-begin/arc-end blocks
    #
    # Plain .cpp implementation files do NOT change module deps and are NOT
    # watched, so editing them will NOT re-trigger this expensive scan.
    #
    # CAVEAT: adding a brand-new .ixx/.ixx.arc file requires
    #   bazel clean --expunge
    # to force rediscovery (since we are not watching directory structure).
    list_result = rctx.execute(
        ["python3", str(list_script), str(workspace)],
        working_directory = str(workspace),
        quiet = True,
    )
    if list_result.return_code != 0:
        fail("arc_module_scan: file listing failed:\n" + list_result.stderr)

    for line in list_result.stdout.splitlines():
        f = line.strip()
        if f:
            rctx.watch(rctx.path(f))

    result = rctx.execute(
        ["python3", str(script), str(workspace)],
        working_directory = str(workspace),
        quiet = True,
    )

    if result.return_code != 0:
        fail("arc_module_scan: dep scan failed:\n" + result.stderr)

    rctx.file("module_deps.bzl", result.stdout)
    rctx.file("BUILD", "# Generated by arc_module_scan repository rule.\n")

arc_module_scan = repository_rule(
    implementation = _arc_module_scan_impl,
    local = True,
    doc = "Scans C++20 module source files and produces a module dependency map.",
)
