"""Repository rule that scans C++20 module sources to build a precise dep map.

Runs bazel/scan_module_deps.py over the workspace source tree(s) and writes
a generated repository containing module_deps.bzl with:

  MODULE_DIRECT_DEPS      {module_name: [directly-imported module names]}
  FILE_DIRECT_DEPS        {workspace-rel-path: [directly-imported module names]}
  MODULE_SOURCES          {workspace-rel-path: module_name}
  MODULE_PROVIDER_TARGETS {module_name: bazel_target_label}

cpp_module.bzl loads these to compute the minimal PCM set needed by each
compilation action, so that modifying one module only recompiles actions
that genuinely depend on it.

When ARC is consumed as a bazel_dep, the scan walks BOTH the main workspace
(consumer) and ARC's own external workspace, so that ARC's modules
(e.g. arc.ixx) appear in the scan output with their canonical Bazel
short_path (../arc+/lib/modules/arc.ixx).
"""

def _arc_module_scan_impl(rctx):
    main_workspace = rctx.workspace_root

    # Scripts live in ARC's repo; resolve via label so consumers don't need to
    # copy them into their own bazel/ directory.
    script_path      = rctx.path(Label("@arc//bazel:scan_module_deps.py"))
    list_script_path = rctx.path(Label("@arc//bazel:list_module_files.py"))

    rctx.watch(script_path)
    rctx.watch(list_script_path)

    # Root descriptors: (absolute_path, short_path_prefix, repo_label_prefix)
    #   short_path_prefix: prefix prepended to MODULE_SOURCES / FILE_DIRECT_DEPS keys
    #   repo_label_prefix: prefix prepended to generated MODULE_PROVIDER_TARGETS labels
    roots = [(str(main_workspace), "", "")]

    # ARC's own workspace. When ARC is the main module this resolves to the
    # same path as main_workspace and is dropped to avoid double-walking.
    arc_module_path = rctx.path(Label("@arc//:MODULE.bazel"))
    arc_workspace = arc_module_path.dirname
    if str(arc_workspace) != str(main_workspace):
        canonical_name = arc_workspace.basename  # e.g. "arc+"
        roots.append((
            str(arc_workspace),
            "../" + canonical_name + "/",
            "@arc",
        ))

    # Extra external repos opted in by a consumer (via the module extension).
    # Each marker is any file at the repo root; its parent dir is the repo root
    # and its basename is the canonical repo name, which both the short_path
    # prefix ("../<canonical>/") and File.short_path agree on. rctx.path also
    # forces the repo to be fetched and watched before the scan walks it.
    for marker, label_prefix in zip(
            rctx.attr.external_markers, rctx.attr.external_label_prefixes):
        repo_root = rctx.path(marker).dirname
        roots.append((
            str(repo_root),
            "../" + repo_root.basename + "/",
            label_prefix,
        ))

    # Watch only files that actually affect module deps:
    #   .ixx / .ixx.arc — module interface units and ARC DSL sources
    #   arc-embed .cpp  — .cpp files containing arc-begin/arc-end blocks
    #
    # CAVEAT: adding a brand-new .ixx/.ixx.arc file requires
    #   bazel clean --expunge
    # to force rediscovery (since we are not watching directory structure).
    list_args = ["python3", str(list_script_path)]
    for path, _, _ in roots:
        list_args.append("--root=" + path)
    list_result = rctx.execute(list_args, quiet = True)
    if list_result.return_code != 0:
        fail("arc_module_scan: file listing failed:\n" + list_result.stderr)

    for line in list_result.stdout.splitlines():
        f = line.strip()
        if f:
            rctx.watch(rctx.path(f))

    scan_args = ["python3", str(script_path)]
    for path, short_prefix, label_prefix in roots:
        scan_args.append("--root={}|{}|{}".format(path, short_prefix, label_prefix))
    result = rctx.execute(scan_args, quiet = True)

    if result.return_code != 0:
        fail("arc_module_scan: dep scan failed:\n" + result.stderr)

    rctx.file("module_deps.bzl", result.stdout)
    rctx.file("BUILD", "# Generated by arc_module_scan repository rule.\n")

arc_module_scan = repository_rule(
    implementation = _arc_module_scan_impl,
    local = True,
    attrs = {
        # Parallel lists: marker file at each opted-in external repo's root, and
        # the Bazel label prefix (e.g. "@unordered_dense") for provider targets
        # emitted for modules found there.
        "external_markers": attr.label_list(allow_files = True),
        "external_label_prefixes": attr.string_list(),
    },
    doc = "Scans C++20 module source files and produces a module dependency map.",
)

# Module extension so consumers can opt external repos into the scan (so their
# C++20 modules land in MODULE_SOURCES / MODULE_PROVIDER_TARGETS like in-tree
# units, no per-file module_names needed). Both ARC and the root module use the
# same extension instance; tags from every module are aggregated here.
def _arc_module_scan_ext_impl(module_ctx):
    markers = []
    prefixes = []
    for mod in module_ctx.modules:
        for ext in mod.tags.external:
            markers.append(ext.marker)
            prefixes.append(ext.label_prefix)
    arc_module_scan(
        name = "arc_module_deps",
        external_markers = markers,
        external_label_prefixes = prefixes,
    )

_external_tag = tag_class(attrs = {
    "marker": attr.label(
        mandatory = True,
        doc = "Any file at the external repo's root (e.g. @repo//:LICENSE).",
    ),
    "label_prefix": attr.string(
        mandatory = True,
        doc = "Label prefix for provider targets, e.g. \"@unordered_dense\".",
    ),
})

arc_module_scan_ext = module_extension(
    implementation = _arc_module_scan_ext_impl,
    tag_classes = {"external": _external_tag},
    doc = "Opt external repos into the ARC module scan and create @arc_module_deps.",
)
