"""Repository rule to discover the C++23 std module source paths."""


def _arc_std_paths_impl(rctx):
    # --- GCC: find bits/std.cc ---
    # Ask GCC for its C++ header search paths via -v, then look for bits/std.cc
    # in each one. This works for any GCC installation prefix (distro packages,
    # custom builds, /opt/...), unlike hard-coding /usr/include/c++/<N>/.
    gcc_std = ""
    res = rctx.execute(["g++", "-v", "-E", "-x", "c++", "/dev/null"])
    if res.return_code == 0 or res.stderr:
        in_search = False
        for line in (res.stderr or "").split("\n"):
            if "#include" in line and "search starts here" in line:
                in_search = True
                continue
            if "End of search list" in line:
                break
            if in_search:
                dir_path = line.strip()
                if dir_path:
                    candidate = dir_path + "/bits/std.cc"
                    if rctx.execute(["test", "-f", candidate]).return_code == 0:
                        gcc_std = candidate
                        break

    # Fallback: broad filesystem search
    if not gcc_std:
        res = rctx.execute(["sh", "-c",
            "find /usr/include /usr/local/include /opt -name std.cc -path '*/bits/*' 2>/dev/null | sort -rV | head -1"])
        if res.return_code == 0:
            gcc_std = res.stdout.strip()

    # --- Clang: resolve std.cppm from --print-resource-dir ---
    clang_std = ""
    res = rctx.execute(["clang++", "--print-resource-dir"])
    if res.return_code == 0:
        # resource_dir is like /usr/lib/llvm-21/lib/clang/21 — go up 3 levels
        parts = [p for p in res.stdout.strip().split("/") if p]
        if len(parts) >= 3:
            llvm_root = "/" + "/".join(parts[:-3])
            candidate = llvm_root + "/share/libc++/v1/std.cppm"
            if rctx.execute(["test", "-f", candidate]).return_code == 0:
                clang_std = candidate
    if not clang_std:
        res = rctx.execute(["sh", "-c",
            "find /usr/lib/llvm-* -name std.cppm -path '*/libc++/v1/*' 2>/dev/null | sort -rV | head -1"])
        if res.return_code == 0:
            clang_std = res.stdout.strip()

    rctx.file("std_paths.bzl", """
# Auto-generated by bazel/std_paths.bzl — do not edit manually.
GCC_STD_CPPM = "{gcc}"
CLANG_STD_CPPM = "{clang}"
""".format(gcc = gcc_std, clang = clang_std))
    rctx.file("BUILD", "# Generated by arc_std_paths repository rule.\n")


arc_std_paths = repository_rule(
    implementation = _arc_std_paths_impl,
    local = True,
    doc = "Discovers the C++23 std module source paths for GCC (bits/std.cc) and Clang (std.cppm).",
)
